### ISSUE TITLE
Establish a standardilzed process

### ISSUE THREAD

**Issue by Vghxv** [BioTechCo/main_project#39]
## Tasks
- [ ] split_dataset.ipynb
- [ ] basic_dbeta.ipynb
- [ ] basic_dbeta_no_champ.ipynb
- [ ] set_dbeta_threshold.ipynb
- [ ] GO_distance_matrix.r
- [ ] GO_cluster.ipynb

**Comment by Vghxv** [comment]
completed
